// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtGYplx9sABKsJ8uSLVX3DstFoBVPD9vY',
    appId: '1:589201056291:web:d226b1d90287b9cd374796',
    messagingSenderId: '589201056291',
    projectId: 'notetaking-mynotes-flutter',
    authDomain: 'notetaking-mynotes-flutter.firebaseapp.com',
    storageBucket: 'notetaking-mynotes-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3d-m3FKm0_V6pbWAg6hGFtQJH-r5QLnw',
    appId: '1:589201056291:android:a7e7f9d0b3556b42374796',
    messagingSenderId: '589201056291',
    projectId: 'notetaking-mynotes-flutter',
    storageBucket: 'notetaking-mynotes-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAWQUHYuVy-YNS9TUZWJmK12UHGdB7NnE',
    appId: '1:589201056291:ios:1049ad2589e608df374796',
    messagingSenderId: '589201056291',
    projectId: 'notetaking-mynotes-flutter',
    storageBucket: 'notetaking-mynotes-flutter.appspot.com',
    iosClientId: '589201056291-ge8cgn3m1g4uirhi2sl74q8sjduod13a.apps.googleusercontent.com',
    iosBundleId: 'me.amartyaayushi.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAWQUHYuVy-YNS9TUZWJmK12UHGdB7NnE',
    appId: '1:589201056291:ios:1049ad2589e608df374796',
    messagingSenderId: '589201056291',
    projectId: 'notetaking-mynotes-flutter',
    storageBucket: 'notetaking-mynotes-flutter.appspot.com',
    iosClientId: '589201056291-ge8cgn3m1g4uirhi2sl74q8sjduod13a.apps.googleusercontent.com',
    iosBundleId: 'me.amartyaayushi.mynotes',
  );
}
